### PR TITLE
Remove only the highlighters added by AceJump when the jump session ends

### LINKED ISSUE #406: Conflict with other plugins
AceJump calls `markupModel.removeAllHighlighters()` to remove all highlights when the jump action ends.
But some highlighters are added by other plugins will also be removed unexpectedly, which could make other plugins not work fine.

AceJump should remove the highlighters added by itself only.

See: https://github.com/huoguangjin/MultiHighlight/issues/4

https://github.com/acejump/AceJump/blob/1341c6aff4642ec27fa4a915981a96a0c7a65541/src/main/kotlin/org/acejump/view/TextHighlighter.kt#L150-L154

### PR DESCRIPTION
**Pull request by huoguangjin**
Fix #406

### CODE REVIEW

**Comment by huoguangjin** [comment]
I am not quite sure if the remove action should be surrounded with `DocumentUtil.executeInBulk`.

**Comment by breandan** [comment]
Hi @huoguangjin, thank you for the PR! Any chance we can add a test for this?

**Comment by huoguangjin** [comment]
uh.. I don't know much about how to test AceJump with intellij idea test suites.
Should I add test case to `ExternalUsageTest.kt`?

**Comment by breandan** [comment]
Yes, that seems like a good place to put it. I would just create a mock editor instance, add some highlighters programmatically using the same technique your plugin uses and check to see they are restored after AceJump exits.

**Comment by huoguangjin** [comment]
Hi, I add a simple test case to check if existed highlighters are removed when the session ends. This test case passes successfully, and fails as expected without the PR commits.

But please note that I dispose the highlighter manually at last because `BaseTest.resetEditor` checks if `markupModel.allHighlighters` empty when tears down. It seems that `BaseTest.kt` takes `markupModel.allHighlighters` as the highlighters added by AceJump. Maybe It needs changes, `String.search` and `String.assertCorrectNumberOfTags` are the same.

**Comment by breandan** [comment]
Okay, thanks for the clarification. In that case, feel free to modify `BaseTest.resetEditor` to check that the correct highlighters are preserved. I think the invariant we want to check is `markupModel.allHighlighters` are the same before and after each AceJump action. Otherwise, LGTM!

**Comment by huoguangjin** [comment]
Sorry, I can't get your idea. you mean we should mark the number of highlighters before the AceJump session starts, and then check if the number is the same when test case tears down?

**Comment by huoguangjin** [comment]
I don't think it is a good idea. Because all test cases call `resetEditor` from `tearDown`, but not all test cases store `oldHighlighters`, it may be initialized as an empty array in `setUp`. While in this new test case, I store `existedHighlighter` as `oldHighlighters` after `setUp` and before starting an AceJump session, which is a little bit unusual.

How about calling `markupModel.allHighlighters` with a filter comparing the layer is equal to `TextHighlighter.LAYER` to find out those highlighters added by AceJump. The only problem is that `TextHighlighter.LAYER` is private.

**Pull request merged**
